CREATE DATABASE QUANLYNHANSU
ON PRIMARY (NAME=QLNS_Data, FILENAME='E:\QuanLyNhanSu.mdf', SIZE=8192KB, MAXSIZE=15MB, FILEGROWTH=5MB) 
LOG ON  ( NAME=QLNS_Log, FILENAME= 'E:\QuanLyNhanSu_log.ldf', SIZE=8192KB, MAXSIZE=15MB,  FILEGROWTH=5MB)

USE QUANLYNHANSU

CREATE TABLE NHANVIEN(
    MANV VARCHAR(5) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    CCCD VARCHAR(12) UNIQUE NOT NULL,
    DIENTHOAI VARCHAR(10) UNIQUE NOT NULL,
    GIOITINH NVARCHAR(3) CHECK (GIOITINH IN (N'Nam',N'Nữ')),
    EMAIL VARCHAR(100) CHECK (EMAIL LIKE '%@%' AND EMAIL LIKE '%.com' AND EMAIL NOT LIKE '% %') UNIQUE NOT NULL,
    NGAYSINH DATE,
    PHONGBAN NVARCHAR(25) CHECK (PHONGBAN IN (N'Giám đốc',N'Tài chính',N'Kỹ thuật',N'Kinh doanh',N'Marketing',N'Nhân sự',N'Hành chính')) NOT NULL,
    CHUCVU NVARCHAR(25) CHECK (CHUCVU IN (N'Giám đốc',N'Trưởng phòng',N'Quản lý',N'Nhân viên',N'Phó phòng',N'Thực tập sinh')),
    THAMNIEN INT NOT NULL 
);

CREATE TABLE TAIKHOAN(
    TENTAIKHOAN VARCHAR(5) PRIMARY KEY,
    PASS VARCHAR(10)
);
ALTER TABLE TAIKHOAN ADD CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY (TENTAIKHOAN) REFERENCES NHANVIEN(MANV)

CREATE TABLE HOPDONG(
    MAHD VARCHAR(5) PRIMARY KEY,
    LOAIHD NVARCHAR(25) CHECK (LOAIHD IN (N'Thực tập',N'Ngắn hạn',N'Dài hạn')),
    NGAYKI DATE,
    THOIHAN FLOAT,
    MANV VARCHAR(5), 
    NGAY_HIEU_LUC DATE,
    NGAY_HET_HAN DATE,
    LUONGCB MONEY
);
ALTER TABLE HOPDONG ADD CONSTRAINT FK_HOPDONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

CREATE TABLE CONG_NGAY(
    MANV VARCHAR(5) NOT NULL,
    NGAYLAM DATE NOT NULL,
    GIOCHINH INT,
    TANGCA INT,
    PRIMARY KEY (MANV, NGAYLAM) 
);
ALTER TABLE CONG_NGAY ADD CONSTRAINT FK_CONGNGAY_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

CREATE TABLE LUONG(
    MANV VARCHAR(5) NOT NULL,
    THANG VARCHAR(7) NOT NULL CHECK (THANG LIKE '[0-1][0-9]/20[0-2][0-9]'),
    TONGGIOCHINH INT,
    TONGTANGCA INT,
    TONGLUONG MONEY,
    PHUCAP MONEY,
    KHAUTRU MONEY,
    THUCNHAN MONEY,
    PRIMARY KEY (MANV, THANG)
);
ALTER TABLE LUONG ADD CONSTRAINT FK_LUONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

CREATE TABLE CHITIETLUONG(
    MANV VARCHAR(5) NOT NULL,
    THANG VARCHAR(7) NOT NULL CHECK(THANG LIKE '[0-1][0-9]/20[0-2][0-9]'),
    LUONGCHINH MONEY,
    LUONGTANGCA MONEY,
    PC_THAMNIEN MONEY,
    PC_PHUNU MONEY,
    PC_CHUYENCAN MONEY,
    PC_THUONG MONEY,
    KT_THUE MONEY,
    KT_BHYT MONEY,
    KT_BHXH MONEY,
    KT_BHTN MONEY,
    KT_CONGDOAN MONEY,
    KT_KHAC MONEY,
    PRIMARY KEY (MANV, THANG) 
);
ALTER TABLE CHITIETLUONG ADD CONSTRAINT FK_CHITIETLUONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

INSERT INTO NHANVIEN (MANV, HOTEN, CCCD, DIENTHOAI, GIOITINH, EMAIL, NGAYSINH, PHONGBAN, CHUCVU, THAMNIEN) VALUES
('NV001', N'Nguyễn Văn An', '046284957482', '0987654321', N'Nam', 'an.nguyen@company.com', '1990-05-15', N'Giám đốc', N'Giám đốc', 0),
('NV002', N'Trần Thị Bích', '582658694920', '0901234567', N'Nữ', 'bich.tran@company.com', '1980-11-20', N'Tài chính', N'Quản lý', 0),
('NV003', N'Lê Văn Cường', '294759204659', '0912345678', N'Nam', 'cuong.le@company.com', '1995-02-10', N'Nhân sự', N'Nhân viên', 0),
('NV004', N'Phạm Thu Diễm', '038242845964', '0968889999', N'Nữ', 'diem.pham@company.com', '1997-07-25', N'Marketing', N'Nhân viên', 0),
('NV005', N'Hoàng Đình Em', '936241056493', '0977665544', N'Nam', 'em.hoang@company.com', '2000-01-01', N'Kỹ thuật', N'Thực tập sinh', 0);
